In [1]:
import numpy as np
import Quaternion

In [51]:
colmap = '/home/rozenberszki/D_Project/wsnsl/Dataset/07f5b601ee/pose.txt'#
arkit = '/home/rozenberszki/D_Project/wsnsl/Dataset/07f5b601ee/traj.txt'

In [52]:
colmap = np.loadtxt(colmap).reshape(-1,4,4)
arkit = np.loadtxt(arkit).reshape(-1,4,4)

In [69]:
R_roll = [[-1, 0, 0],
          [0, -1, 0],
          [0, 0, 1]]
R = colmap[0][:3,:3]
T = colmap[0][:3,3]
n = np.eye(4)
n[:3,:3] = R.T @ R_roll
n[:3,3] = -R.T @ T

In [72]:
colmap[1], arkit[10]

(array([[ 0.90426923,  0.2109949 , -0.37118514,  1.39694242],
        [ 0.42644666, -0.48906413,  0.76089493,  2.37637735],
        [-0.02098818, -0.84634449, -0.53222374,  1.47317183],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.82877284,  0.28706285, -0.48034415,  3.1780863 ],
        [-0.01761256, -0.84458655, -0.5351293 , -0.59987956],
        [-0.55930793,  0.45196077, -0.69491446, -2.553681  ],
        [ 0.        ,  0.        ,  0.        ,  0.9999997 ]]))

In [70]:
n, arkit[0]

(array([[-0.89634522, -0.44235973, -0.02971733, -2.26261004],
        [-0.20560163,  0.47412001, -0.85611812,  2.10340015],
        [ 0.39280175, -0.76126746, -0.51592509, -0.49812704],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.81875277,  0.27931443, -0.50162464,  3.1800714 ],
        [-0.02646829, -0.8543969 , -0.51894647, -0.5956651 ],
        [-0.57353574,  0.43816608, -0.69214684, -2.5539694 ],
        [ 0.        ,  0.        ,  0.        ,  0.99999976]]))

In [53]:
colmap_pose = transform_arkit_to_colmap(arkit[10])

In [55]:
colmap_pose, colmap[1]

(array([[ 0.81875277, -0.50162464, -0.27931443,  3.1800714 ],
        [-0.57353574, -0.69214684, -0.43816608,  2.5539694 ],
        [ 0.02646829,  0.51894647, -0.8543969 , -0.5956651 ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.90426923,  0.2109949 , -0.37118514,  1.39694242],
        [ 0.42644666, -0.48906413,  0.76089493,  2.37637735],
        [-0.02098818, -0.84634449, -0.53222374,  1.47317183],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [45]:
toArkit(colmap[0])

(array([ 1.39995203,  1.47652391, -2.37735946]),
 array([ 0.84946899, -0.124348  , -0.190696  , -0.475999  ]))

In [46]:
import numpy as np
from scipy.spatial.transform import Rotation as R

def pose_matrix_from_translation_quaternion(translation, quaternion):
    # Create a rotation matrix from the quaternion
    rotation_matrix = R.from_quat(quaternion).as_matrix()
    
    # Create a 4x4 identity matrix
    pose_matrix = np.eye(4)
    
    # Set the translation values in the pose matrix
    pose_matrix[:3, 3] = translation
    
    # Set the rotation values in the pose matrix
    pose_matrix[:3, :3] = rotation_matrix
    
    return pose_matrix


In [48]:
pose_matrix_from_translation_quaternion(*toArkit(colmap[0]))

array([[ 0.89634522, -0.39280175, -0.20560163,  1.39995203],
       [-0.02971733, -0.51592506,  0.8561181 ,  1.47652391],
       [-0.44235972, -0.76126744, -0.47411999, -2.37735946],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [49]:
arkit[0]

array([[ 0.81875277,  0.27931443, -0.50162464,  3.1800714 ],
       [-0.02646829, -0.8543969 , -0.51894647, -0.5956651 ],
       [-0.57353574,  0.43816608, -0.69214684, -2.5539694 ],
       [ 0.        ,  0.        ,  0.        ,  0.99999976]])

In [29]:
transform_arkit_to_colmap(arkit[0])

(array([ 3.1800714,  2.5539694, -0.5956651]),
 array([[ 0.81875277, -0.50162464, -0.27931443],
        [-0.57353574, -0.69214684, -0.43816608],
        [ 0.02646829,  0.51894647, -0.8543969 ]]))

In [30]:
colmap[0]

array([[ 0.89634522,  0.20560163, -0.39280175,  1.39995203],
       [ 0.44235973, -0.47412001,  0.76126746,  2.37735946],
       [-0.02971733, -0.85611812, -0.51592509,  1.47652391],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])