In [83]:
import numpy as np
import glob

path_to_traj = f"/home/rozenberszki/D_Project/wsnsl/Dataset/traj.txt"
path_to_COL = f"/home/rozenberszki/D_Project/wsnsl/Dataset/pose.txt"
T_wc = np.loadtxt(path_to_traj).reshape(-1, 4, 4)
T_wcCOL= np.loadtxt(path_to_COL).reshape(-1, 4, 4)
#s = np.ones((4, 4))
'''s=np.array([[1, 1, -1, 1],
            [1, 1, -1, 1],
            [-1, -1, 1, -1],
            [0, 0, 0, 1]])
T_wc = s * T_wc'''
'''
T_wc[:,1:3]*=-1
#T_wc[:,:3,3]=0
color_paths = sorted(glob.glob(f"/home/rozenberszki/D_Project/wsnsl/Dataset/color_path/*.jpg"))
print(color_paths)
depth_paths = sorted(glob.glob(f"/home/rozenberszki/D_Project/wsnsl/Dataset/color_path/*.png"))
#  y,z 
T_wc[:,:3, 3] *= 1/2
print(T_wc[0])
'''
print(T_wcCOL[:,:3,:3].shape)
print(T_wcCOL[:,:3,3].T.shape)
'''
for i in range(T_wcCOL.shape[0]):
    T_wcCOL[i, :3, :3] = T_wcCOL[i, :3, :3].T

# Correct matrix multiplication after the transposition is fixed
for i in range(T_wcCOL.shape[0]):
    T_wcCOL[i, :3, 3] = -T_wcCOL[i, :3, :3] @ T_wcCOL[i, :3, 3]'''

(946, 3, 3)
(3, 946)


'\nfor i in range(T_wcCOL.shape[0]):\n    T_wcCOL[i, :3, :3] = T_wcCOL[i, :3, :3].T\n\n# Correct matrix multiplication after the transposition is fixed\nfor i in range(T_wcCOL.shape[0]):\n    T_wcCOL[i, :3, 3] = -T_wcCOL[i, :3, :3] @ T_wcCOL[i, :3, 3]'

In [85]:
#T_wc[:9460:10]-=T_wcCOL
for i in range(20):
    print("COLMAP:", T_wcCOL[i])
    print("IPHONE:" , T_wc[i*10])
    print("\n\n\n")

COLMAP: [[-0.950703 -0.309975 -0.008887  0.350173]
 [ 0.283283 -0.856469 -0.431523  0.929442]
 [ 0.12615  -0.412767  0.902058 -0.101077]
 [ 0.        0.        0.        1.      ]]
IPHONE: [[ 0.63281906  0.5936474  -0.4971145   0.39389375]
 [ 0.03214595 -0.6616073  -0.7491611   0.06876414]
 [-0.7736321   0.45810315 -0.43776107  0.6076599 ]
 [ 0.          0.          0.          1.        ]]




COLMAP: [[-0.94288  -0.33304  -0.007832  0.34196 ]
 [ 0.306012 -0.85659  -0.415463  0.931543]
 [ 0.131657 -0.394129  0.909576 -0.107738]
 [ 0.        0.        0.        1.      ]]
IPHONE: [[ 0.6443237   0.5956896  -0.47958398  0.39054307]
 [ 0.03437619 -0.649036   -0.7599806   0.07035726]
 [-0.76397985  0.47318733 -0.43866676  0.6088659 ]
 [ 0.          0.          0.          1.        ]]




COLMAP: [[-0.931353 -0.363816 -0.014794  0.332623]
 [ 0.339001 -0.851567 -0.399889  0.934831]
 [ 0.132888 -0.377453  0.916444 -0.109968]
 [ 0.        0.        0.        1.      ]]
IPHONE: [[ 0.6458365   