In [6]:
import open3d as o3d

# Load the PCD file
pcd_path = "/home/rozenberszki/project/wsnsl/Datasets/TUM_RGBD/freiburg2_coke_pc/1311871928.522561045.pcd"  # Change this to the path of your PCD file
pcd = o3d.io.read_point_cloud(pcd_path)


In [11]:
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.


In [10]:
import numpy as np
# Access the point data
points = pcd.points

# Print the first 10 points
print(np.asarray(points[:10]))


[[ 2.17415047 -1.67916012  3.99800014]
 [ 2.18176579 -1.67916012  3.99800014]
 [ 2.16419053 -1.65984011  3.95200014]
 [ 2.17171812 -1.65984011  3.95200014]
 [ 2.20461154 -1.67916012  3.99800014]
 [ 2.23823333 -1.69889998  4.04500008]
 [ 2.21984196 -1.67916012  3.99800014]
 [ 2.22745728 -1.67916012  3.99800014]
 [ 2.26134777 -1.69889998  4.04500008]
 [ 2.2426877  -1.67916012  3.99800014]]
