In [2]:
import pandas as pd
import numpy as np
import json

In [2]:
import torch
torch.ones_like(torch.tensor([1, 2, 3]))

tensor([1, 1, 1])

In [3]:
path = '/home/rozenberszki/project/panoptic-lifting/data/replica/room_0/splits.json'

In [4]:
data = json.load(open(path, 'r'))['test']
data

['0_0000',
 '0_0004',
 '0_0008',
 '0_0012',
 '0_0016',
 '0_0020',
 '0_0024',
 '0_0028',
 '0_0032',
 '0_0036',
 '0_0040',
 '0_0044',
 '0_0048',
 '0_0052',
 '0_0056',
 '0_0060',
 '0_0064',
 '0_0068',
 '0_0072',
 '0_0076',
 '0_0080',
 '0_0084',
 '0_0088',
 '0_0092',
 '0_0096',
 '0_0100',
 '0_0104',
 '0_0108',
 '0_0112',
 '0_0116',
 '0_0120',
 '0_0124',
 '0_0128',
 '0_0132',
 '0_0136',
 '0_0140',
 '0_0144',
 '0_0148',
 '0_0152',
 '0_0156',
 '0_0160',
 '0_0164',
 '0_0168',
 '0_0172',
 '0_0176',
 '0_0180',
 '0_0184',
 '0_0188',
 '0_0192',
 '0_0196',
 '0_0200',
 '0_0204',
 '0_0208',
 '0_0212',
 '0_0216',
 '0_0220',
 '0_0224',
 '0_0228',
 '0_0232',
 '0_0236',
 '0_0240',
 '0_0244',
 '0_0248',
 '0_0252',
 '0_0256',
 '0_0260',
 '0_0264',
 '0_0268',
 '0_0272',
 '0_0276',
 '0_0280',
 '0_0284',
 '0_0288',
 '0_0292',
 '0_0296',
 '0_0300',
 '0_0304',
 '0_0308',
 '0_0312',
 '0_0316',
 '0_0320',
 '0_0324',
 '0_0328',
 '0_0332',
 '0_0336',
 '0_0340',
 '0_0344',
 '0_0348',
 '0_0352',
 '0_0356',
 '0_0360',

In [4]:
def convert_image_name(image_name):
    # Split the image name at the underscore
    prefix, number = image_name.split('_')
    
    # Pad the number with one additional zero
    padded_number = f'{int(number):06d}'  # Ensures the number has 5 digits
    
    # Create the new image names
    frame_name = f'frame{padded_number}'
    depth_name = f'depth{padded_number}'
    
    return frame_name, depth_name

# Example usage
original_name = '0_0001'
frame_name, depth_name = convert_image_name(original_name)

print('Frame:', frame_name)
print('Depth:', depth_name)

Frame: frame000001
Depth: depth000001


In [5]:
frames, depths = [], []
for d in data:
    frame_name, depth_name = convert_image_name(d)
    frames.append(frame_name+'.jpg')
    depths.append(depth_name+'.png')

print(frames[-5:])
print(depths[-5:])

['frame000894.jpg', 'frame000895.jpg', 'frame000897.jpg', 'frame000898.jpg', 'frame000899.jpg']
['depth000894.png', 'depth000895.png', 'depth000897.png', 'depth000898.png', 'depth000899.png']


## move test images out of results folder

In [6]:
depths

['depth000001.png',
 'depth000002.png',
 'depth000003.png',
 'depth000005.png',
 'depth000006.png',
 'depth000007.png',
 'depth000009.png',
 'depth000010.png',
 'depth000011.png',
 'depth000013.png',
 'depth000014.png',
 'depth000015.png',
 'depth000017.png',
 'depth000018.png',
 'depth000019.png',
 'depth000021.png',
 'depth000022.png',
 'depth000023.png',
 'depth000025.png',
 'depth000026.png',
 'depth000027.png',
 'depth000029.png',
 'depth000030.png',
 'depth000031.png',
 'depth000033.png',
 'depth000034.png',
 'depth000035.png',
 'depth000037.png',
 'depth000038.png',
 'depth000039.png',
 'depth000041.png',
 'depth000042.png',
 'depth000043.png',
 'depth000045.png',
 'depth000046.png',
 'depth000047.png',
 'depth000049.png',
 'depth000050.png',
 'depth000051.png',
 'depth000053.png',
 'depth000054.png',
 'depth000055.png',
 'depth000057.png',
 'depth000058.png',
 'depth000059.png',
 'depth000061.png',
 'depth000062.png',
 'depth000063.png',
 'depth000065.png',
 'depth000066.png',


In [7]:
import os
import shutil


In [8]:
# Paths to the directories
source_folder = '/home/rozenberszki/project/wsnsl/Datasets/Replica/room0_panoptic/results'
destination_folder = '/home/rozenberszki/project/wsnsl/Datasets/Replica/room0_panoptic/test_results_org_pan'

# Ensure the destination folder exists
if not os.path.exists(destination_folder):
    os.makedirs(destination_folder)

# List of image names in the subset
subset_list = depths  # Add your image names here


In [9]:
# Loop through all files in the source folder
for file_name in os.listdir(source_folder):
    if file_name not in frames and file_name not in depths:
        # Full path of the file
        source_file_path = os.path.join(source_folder, file_name)
        destination_file_path = os.path.join(destination_folder, file_name)
        
        # Move the file
        shutil.move(source_file_path, destination_file_path)
        print(f'Moved: {file_name}')


In [16]:
t = np.loadtxt('/home/rozenberszki/project/wsnsl/Datasets/Replica/room0_panoptic/traj_full.txt')

In [17]:
t = t.reshape(-1,4,4)
t.shape

(900, 4, 4)

In [20]:
n = [int(d.split('_')[1]) for d in data]
n = np.array(n)
t_split = t[n]

In [13]:
np.savetxt('/home/rozenberszki/project/wsnsl/Datasets/Replica/room0_panoptic/traj.txt', t_split.reshape(-1,16))

In [24]:
indices = np.arange(len(t))
indices_to_store = indices[~np.isin(indices, n)]
t_test = t[indices_to_store]


In [27]:
indices_to_store, data

(array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
        104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
        156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200, 204,
        208, 212, 216, 220, 224, 228, 232, 236, 240, 244, 248, 252, 256,
        260, 264, 268, 272, 276, 280, 284, 288, 292, 296, 300, 304, 308,
        312, 316, 320, 324, 328, 332, 336, 340, 344, 348, 352, 356, 360,
        364, 368, 372, 376, 380, 384, 388, 392, 396, 400, 404, 408, 412,
        416, 420, 424, 428, 432, 436, 440, 444, 448, 452, 456, 460, 464,
        468, 472, 476, 480, 484, 488, 492, 496, 500, 504, 508, 512, 516,
        520, 524, 528, 532, 536, 540, 544, 548, 552, 556, 560, 564, 568,
        572, 576, 580, 584, 588, 592, 596, 600, 604, 608, 612, 616, 620,
        624, 628, 632, 636, 640, 644, 648, 652, 656, 660, 664, 668, 672,
        676, 680, 684, 688, 692, 696, 700, 704, 708

In [26]:
t_test

array([[[-3.83733105e-01,  5.73003513e-02,  9.21664567e-01,
          1.81724055e+00],
        [-9.23444045e-01, -2.38109086e-02, -3.82993650e-01,
          2.11536135e+00],
        [-0.00000000e+00, -9.98072999e-01,  6.20507021e-02,
         -4.46253861e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]],

       [[-4.01562646e-01,  1.77286131e-02,  9.15659946e-01,
          1.74565446e+00],
        [-9.15831557e-01, -7.77342593e-03, -4.01487400e-01,
          2.14121925e+00],
        [-0.00000000e+00, -9.99812618e-01,  1.93579408e-02,
         -4.33343688e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]],

       [[-4.01464924e-01, -1.88840628e-02,  9.15679697e-01,
          1.66424670e+00],
        [-9.15874399e-01,  8.27765120e-03, -4.01379578e-01,
          2.14722974e+00],
        [-0.00000000e+00, -9.99787414e-01, -2.06186163e-02,
         -4.11490569e-01],
        [ 0.00000000e+00,  0.00000000e+

In [25]:
np.savetxt('/home/rozenberszki/project/wsnsl/Datasets/Replica/room0_panoptic/traj_test.txt', t_test.reshape(-1,16))